# Wrapping and line width
max_width = 80
wrap_comments = true
format_code_in_doc_comments = true
format_strings = true

# Structural widths
chain_width = 40
fn_call_width = 40
struct_lit_width = 40
struct_variant_width = 40

# Indentation and style
hard_tabs = false
tab_spaces = 4
newline_style = "Unix"
indent_style = "Block"
use_small_heuristics = "Max"

# Import options
reorder_imports = true
imports_granularity = "Crate"

fn_params_layout = "Vertical"
